// Generated by scripts/gen_shops.py from scrapers/vendors/*.yaml. Do not edit by
// hand: run `python scripts/gen_shops.py` after adding or renaming a vendor.
//
// Why this file exists rather than an API call: scripts/prerender.js needs the
// full shop list offline, at build time, and a slug has to be stable across a
// vendor rename. `name` is the join key to the API's vendor_name and to
// bikes.vendor_name, so it must match the YAML exactly.
//
// Deliberately dependency-free, for the same reason content/categories.js is:
// prerender.js imports this with bare `node`, outside Vite. No JSX, no imports,
// no import.meta.env.

export const SHOPS = [
  { slug: "99-bikes", path: "/shops/99-bikes", name: "99 Bikes", cities: ["Brisbane", "Melbourne", "Sydney", "Adelaide", "Canberra", "Hobart", "Gold Coast", "Sunshine Coast"], url: "https://www.99bikes.com.au" },
  { slug: "abc-bikes", path: "/shops/abc-bikes", name: "ABC Bikes", cities: ["Sydney"], url: "https://www.abcbikes.com.au" },
  { slug: "alchemy-cycle-trader", path: "/shops/alchemy-cycle-trader", name: "Alchemy Cycle Trader", cities: ["Melbourne"], url: "https://alchemycycletrader.com.au" },
  { slug: "ampd-bros", path: "/shops/ampd-bros", name: "Ampd Bros", cities: ["Gold Coast"], url: "https://ampdbros.com.au" },
  { slug: "bam-cycles", path: "/shops/bam-cycles", name: "BAM Cycles", cities: ["Melbourne"], url: "https://www.bamcycles.com.au" },
  { slug: "bay-bike-co", path: "/shops/bay-bike-co", name: "Bay Bike Co", cities: ["Newcastle"], url: "https://www.baybikeco.com.au" },
  { slug: "bayside-cycles", path: "/shops/bayside-cycles", name: "Bayside Cycles", cities: ["Melbourne"], url: "https://baysidecycles.com.au" },
  { slug: "bicycle-centre-australia", path: "/shops/bicycle-centre-australia", name: "Bicycle Centre Australia", cities: ["Melbourne", "Geelong", "Warrnambool", "Bendigo", "Shepparton", "Armidale", "Newcastle", "Townsville", "Adelaide", "Burnie", "Alice Springs"], url: "https://bicycle-centre.com.au" },
  { slug: "bicycle-centre-belmont", path: "/shops/bicycle-centre-belmont", name: "Bicycle Centre Belmont", cities: ["Geelong"], url: "https://bicyclecentrebelmont.com.au" },
  { slug: "bicycle-express", path: "/shops/bicycle-express", name: "Bicycle Express", cities: ["Adelaide"], url: "https://www.bicycleexpress.com.au" },
  { slug: "bicycle-fix", path: "/shops/bicycle-fix", name: "Bicycle Fix", cities: ["Adelaide Hills"], url: "https://bicyclefix.com.au" },
  { slug: "bicycle-superstore", path: "/shops/bicycle-superstore", name: "Bicycle Superstore", cities: ["Melbourne"], url: "https://bicyclesuperstore.com.au" },
  { slug: "bicycle-workshop", path: "/shops/bicycle-workshop", name: "Bicycle Workshop", cities: ["Melbourne"], url: "https://bicycleworkshop.com.au" },
  { slug: "bike-central-gc", path: "/shops/bike-central-gc", name: "Bike Central GC", cities: ["Gold Coast"], url: "https://bikecentralgc.com.au" },
  { slug: "bike-force-clarkson", path: "/shops/bike-force-clarkson", name: "Bike Force Clarkson", cities: ["Perth"], url: "https://www.bikeforceclarkson.com.au" },
  { slug: "bike-force-joondalup", path: "/shops/bike-force-joondalup", name: "Bike Force Joondalup", cities: ["Perth"], url: "https://bikeforcejoondalup.com.au" },
  { slug: "bike-line", path: "/shops/bike-line", name: "Bike Line", cities: ["Toowoomba"], url: "https://www.bikeline.com.au" },
  { slug: "bike-now", path: "/shops/bike-now", name: "Bike Now", cities: ["Melbourne"], url: "https://bikenow.com.au" },
  { slug: "bike-zone-fitzroy", path: "/shops/bike-zone-fitzroy", name: "Bike Zone Fitzroy", cities: ["Melbourne"], url: "https://www.bikezonefitzroy.com.au" },
  { slug: "bikeology", path: "/shops/bikeology", name: "Bikeology", cities: ["Brisbane"], url: "https://www.bikeology.com.au" },
  { slug: "bikes-online", path: "/shops/bikes-online", name: "Bikes Online", cities: ["Brisbane", "Melbourne", "Perth", "Sydney", "Canberra"], url: "https://www.bikesonline.com.au" },
  { slug: "bikes-com-au", path: "/shops/bikes-com-au", name: "Bikes.com.au", cities: ["Melbourne"], url: "https://bikes.com.au" },
  { slug: "canberra-cyclery", path: "/shops/canberra-cyclery", name: "Canberra Cyclery", cities: ["Canberra"], url: "https://canberracyclery.com.au" },
  { slug: "canyon", path: "/shops/canyon", name: "Canyon", cities: [], url: "https://www.canyon.com" },
  { slug: "ccache", path: "/shops/ccache", name: "CCACHE", cities: ["Sydney"], url: "https://ccache.cc" },
  { slug: "crooze", path: "/shops/crooze", name: "Crooze", cities: ["Brisbane"], url: "https://crooze.com.au" },
  { slug: "currumbin-cycles", path: "/shops/currumbin-cycles", name: "Currumbin Cycles", cities: ["Gold Coast"], url: "https://www.currumbincycles.com.au" },
  { slug: "curve-cycling", path: "/shops/curve-cycling", name: "Curve Cycling", cities: ["Melbourne"], url: "https://www.curvecycling.com" },
  { slug: "cycle-world", path: "/shops/cycle-world", name: "Cycle World", cities: ["Sydney"], url: "https://cycleworld.com.au" },
  { slug: "cycle-zone", path: "/shops/cycle-zone", name: "Cycle Zone", cities: ["Sunshine Coast"], url: "https://cyclezone.com.au" },
  { slug: "cyclery-northside", path: "/shops/cyclery-northside", name: "Cyclery Northside", cities: ["Sydney"], url: "https://www.cyclerynorthside.com.au" },
  { slug: "cyclespot", path: "/shops/cyclespot", name: "Cyclespot", cities: ["Sydney"], url: "https://cyclespot.com.au" },
  { slug: "de-grandi-cycle-works", path: "/shops/de-grandi-cycle-works", name: "De Grandi Cycle Works", cities: ["Geelong"], url: "https://degrandi.com.au" },
  { slug: "drift-bikes", path: "/shops/drift-bikes", name: "Drift Bikes", cities: ["Newcastle"], url: "https://driftbikes.com.au" },
  { slug: "ebikes-superstore", path: "/shops/ebikes-superstore", name: "eBikes Superstore", cities: ["Adelaide"], url: "https://www.ebikessuperstore.com.au" },
  { slug: "electric-bikes-brisbane", path: "/shops/electric-bikes-brisbane", name: "Electric Bikes Brisbane", cities: ["Brisbane"], url: "https://www.electricbikesbrisbane.com.au" },
  { slug: "empire-cycles", path: "/shops/empire-cycles", name: "Empire Cycles", cities: ["Perth"], url: "https://empirecycles.com.au" },
  { slug: "epic-cycles", path: "/shops/epic-cycles", name: "Epic Cycles", cities: ["Brisbane"], url: "https://www.epiccycles.com.au" },
  { slug: "evolution-bikes", path: "/shops/evolution-bikes", name: "Evolution Bikes", cities: ["Perth"], url: "https://www.evolutionbikes.com.au" },
  { slug: "fitzroy-cycles", path: "/shops/fitzroy-cycles", name: "Fitzroy Cycles", cities: ["Melbourne"], url: "https://www.fitzroycycles.com.au" },
  { slug: "freedom-machine", path: "/shops/freedom-machine", name: "Freedom Machine", cities: ["Byron Bay"], url: "https://freedommachine.com.au" },
  { slug: "giant-bairnsdale", path: "/shops/giant-bairnsdale", name: "Giant Bairnsdale", cities: ["Bairnsdale"], url: "https://www.giantbairnsdale.com.au" },
  { slug: "giant-ballarat", path: "/shops/giant-ballarat", name: "Giant Ballarat", cities: ["Ballarat"], url: "https://www.giantballarat.com.au" },
  { slug: "giant-bendigo", path: "/shops/giant-bendigo", name: "Giant Bendigo", cities: ["Bendigo"], url: "https://www.giantbendigo.com.au" },
  { slug: "giant-brisbane", path: "/shops/giant-brisbane", name: "Giant Brisbane", cities: ["Brisbane"], url: "https://giantbrisbane.com.au" },
  { slug: "giant-bundaberg", path: "/shops/giant-bundaberg", name: "Giant Bundaberg", cities: ["Bundaberg"], url: "https://www.giantbundaberg.com.au" },
  { slug: "giant-castlemaine", path: "/shops/giant-castlemaine", name: "Giant Castlemaine", cities: ["Castlemaine"], url: "https://www.giantcastlemaine.com.au" },
  { slug: "giant-devonport", path: "/shops/giant-devonport", name: "Giant Devonport", cities: ["Devonport"], url: "https://www.giantdevonport.com.au" },
  { slug: "giant-echuca", path: "/shops/giant-echuca", name: "Giant Echuca", cities: ["Echuca"], url: "https://www.giantechuca.com.au" },
  { slug: "giant-gold-coast", path: "/shops/giant-gold-coast", name: "Giant Gold Coast", cities: ["Gold Coast"], url: "https://www.giantgoldcoast.com.au" },
  { slug: "giant-lygon-st", path: "/shops/giant-lygon-st", name: "Giant Lygon St", cities: ["Melbourne"], url: "https://giantlygonst.com.au" },
  { slug: "giant-mandurah", path: "/shops/giant-mandurah", name: "Giant Mandurah", cities: ["Mandurah"], url: "https://www.giantmandurah.com.au" },
  { slug: "giant-mudgee", path: "/shops/giant-mudgee", name: "Giant Mudgee", cities: ["Mudgee"], url: "https://www.giantmudgee.com.au" },
  { slug: "giant-osborne-park", path: "/shops/giant-osborne-park", name: "Giant Osborne Park", cities: ["Perth"], url: "https://giantosbornepark.com.au" },
  { slug: "giant-ramsgate", path: "/shops/giant-ramsgate", name: "Giant Ramsgate", cities: ["Sydney"], url: "https://www.giantramsgate.com.au" },
  { slug: "giant-rockhampton", path: "/shops/giant-rockhampton", name: "Giant Rockhampton", cities: ["Rockhampton"], url: "https://www.giantrockhampton.com.au" },
  { slug: "giant-south-yarra", path: "/shops/giant-south-yarra", name: "Giant South Yarra", cities: ["Melbourne"], url: "https://giantsthyarra.com.au" },
  { slug: "giant-st-helens", path: "/shops/giant-st-helens", name: "Giant St Helens", cities: ["St Helens"], url: "https://www.giantsthelens.com" },
  { slug: "giant-sunshine-coast", path: "/shops/giant-sunshine-coast", name: "Giant Sunshine Coast", cities: ["Sunshine Coast"], url: "https://www.giantsunshinecoast.com.au" },
  { slug: "giant-sydney", path: "/shops/giant-sydney", name: "Giant Sydney", cities: ["Sydney"], url: "https://www.giantsydney.com.au" },
  { slug: "giant-tamworth", path: "/shops/giant-tamworth", name: "Giant Tamworth", cities: ["Tamworth"], url: "https://www.gianttamworth.com.au" },
  { slug: "giant-tuggerah", path: "/shops/giant-tuggerah", name: "Giant Tuggerah", cities: ["Central Coast"], url: "https://www.gianttuggerah.com.au" },
  { slug: "giant-wollongong", path: "/shops/giant-wollongong", name: "Giant Wollongong", cities: ["Wollongong"], url: "https://www.giantwollongong.com.au" },
  { slug: "glowworm-bicycles", path: "/shops/glowworm-bicycles", name: "Glowworm Bicycles", cities: ["Sydney"], url: "https://glowwormbicycles.com.au" },
  { slug: "happy-wheels", path: "/shops/happy-wheels", name: "Happy Wheels", cities: ["Sydney"], url: "https://www.happywheels.com.au" },
  { slug: "hendry-s", path: "/shops/hendry-s", name: "Hendry's", cities: ["Geelong"], url: "https://hendrys.com.au" },
  { slug: "ivanhoe-cycles", path: "/shops/ivanhoe-cycles", name: "Ivanhoe Cycles", cities: ["Melbourne"], url: "https://ivanhoecycles.com.au" },
  { slug: "jet-cycles", path: "/shops/jet-cycles", name: "Jet Cycles", cities: ["Sydney"], url: "https://jetcycles.com.au" },
  { slug: "just-ride-nerang", path: "/shops/just-ride-nerang", name: "Just Ride Nerang", cities: ["Gold Coast"], url: "https://justridenerang.com.au" },
  { slug: "lakes-bikes", path: "/shops/lakes-bikes", name: "Lakes Bikes", cities: ["Perth"], url: "https://www.lakesbikes.com.au" },
  { slug: "lekker-bikes", path: "/shops/lekker-bikes", name: "Lekker Bikes", cities: ["Melbourne", "Sydney", "Canberra"], url: "https://lekkerbikes.com.au" },
  { slug: "life-cycle-bikes", path: "/shops/life-cycle-bikes", name: "Life Cycle Bikes", cities: ["Margaret River"], url: "https://www.lifecyclebikes.com.au" },
  { slug: "live-life-cycling", path: "/shops/live-life-cycling", name: "Live Life Cycling", cities: ["Brisbane"], url: "https://www.livelifecycling.com.au" },
  { slug: "macarthur-bikes", path: "/shops/macarthur-bikes", name: "Macarthur Bikes", cities: ["Sydney"], url: "https://www.macarthurebikes.com.au" },
  { slug: "mackay-cycles", path: "/shops/mackay-cycles", name: "Mackay Cycles", cities: ["Mackay"], url: "https://www.mackaycycles.com.au" },
  { slug: "mcbain-cycles", path: "/shops/mcbain-cycles", name: "McBain Cycles", cities: ["Hobart"], url: "https://mcbaincycles.com.au" },
  { slug: "melbourne-bicycles", path: "/shops/melbourne-bicycles", name: "Melbourne Bicycles", cities: ["Melbourne"], url: "https://www.melbournebicycles.com.au" },
  { slug: "my-ride", path: "/shops/my-ride", name: "My Ride", cities: [], url: "https://www.myride.com.au" },
  { slug: "off-course", path: "/shops/off-course", name: "Off Course", cities: ["Melbourne"], url: "https://offcourse.bike" },
  { slug: "omafiets", path: "/shops/omafiets", name: "Omafiets", cities: ["Sydney"], url: "https://omafiets.com.au" },
  { slug: "peak-cycles", path: "/shops/peak-cycles", name: "Peak Cycles", cities: ["Melbourne"], url: "https://www.peakcycles.com.au" },
  { slug: "pedal-heads", path: "/shops/pedal-heads", name: "Pedal Heads", cities: ["Brisbane"], url: "https://www.pedalheads.com.au" },
  { slug: "pedal-inn", path: "/shops/pedal-inn", name: "Pedal Inn", cities: ["Brisbane"], url: "https://www.pedalinn.au" },
  { slug: "pedl", path: "/shops/pedl", name: "Pedl", cities: ["Sydney"], url: "https://pedl.com.au" },
  { slug: "planet-cycles", path: "/shops/planet-cycles", name: "Planet Cycles", cities: ["Brisbane"], url: "https://www.planetcycles.com.au" },
  { slug: "pm-cycles", path: "/shops/pm-cycles", name: "PM Cycles", cities: ["Melbourne"], url: "https://pmcycles.com.au" },
  { slug: "progear-bikes", path: "/shops/progear-bikes", name: "Progear Bikes", cities: ["Melbourne"], url: "https://www.progearbikes.com.au" },
  { slug: "reid-cycles", path: "/shops/reid-cycles", name: "Reid Cycles", cities: ["Melbourne", "Brisbane"], url: "https://www.reidcycles.com.au" },
  { slug: "ride-n-roll", path: "/shops/ride-n-roll", name: "Ride 'n' Roll", cities: ["Gold Coast"], url: "https://www.ridenroll.com.au" },
  { slug: "ride-bellerive", path: "/shops/ride-bellerive", name: "Ride Bellerive", cities: ["Hobart"], url: "https://www.ride.net.au" },
  { slug: "ride-union-bike-co", path: "/shops/ride-union-bike-co", name: "Ride Union Bike Co", cities: ["Adelaide Hills"], url: "https://www.rideunionbikeco.com.au" },
  { slug: "river-city-cycles", path: "/shops/river-city-cycles", name: "River City Cycles", cities: ["Brisbane"], url: "https://rivercitycycles.com.au" },
  { slug: "saint-cloud", path: "/shops/saint-cloud", name: "Saint Cloud", cities: ["Melbourne"], url: "https://saintcloud.com.au" },
  { slug: "stealth-electric-bikes", path: "/shops/stealth-electric-bikes", name: "Stealth Electric Bikes", cities: ["Melbourne"], url: "https://stealthelectricbikes.com" },
  { slug: "summit-cycles", path: "/shops/summit-cycles", name: "Summit Cycles", cities: ["Melbourne"], url: "https://summitcycles.bike" },
  { slug: "supreme-cycles", path: "/shops/supreme-cycles", name: "Supreme Cycles", cities: ["Sunshine Coast"], url: "https://supremecycles.com.au" },
  { slug: "the-bicycle-company", path: "/shops/the-bicycle-company", name: "The Bicycle Company", cities: ["Melbourne"], url: "https://thebicyclecompany.com.au" },
  { slug: "the-bike-shop", path: "/shops/the-bike-shop", name: "The Bike Shop", cities: ["Brisbane"], url: "https://www.thebikeshop.au" },
  { slug: "the-mountain-biker", path: "/shops/the-mountain-biker", name: "The Mountain Biker", cities: ["Brisbane"], url: "https://www.themountainbiker.com.au" },
  { slug: "treadly-bike-shop", path: "/shops/treadly-bike-shop", name: "Treadly Bike Shop", cities: ["Adelaide"], url: "https://treadlybikeshop.com.au" },
  { slug: "velectrix", path: "/shops/velectrix", name: "Velectrix", cities: ["Sunshine Coast"], url: "https://velectrix.com.au" },
  { slug: "velofix-rozelle", path: "/shops/velofix-rozelle", name: "Velofix Rozelle", cities: ["Sydney"], url: "https://velofix.com.au" },
  { slug: "venture-cycles", path: "/shops/venture-cycles", name: "Venture Cycles", cities: ["Sunshine Coast"], url: "https://venturecycles.com.au" },
  { slug: "wembley-cycles", path: "/shops/wembley-cycles", name: "Wembley Cycles", cities: ["Perth"], url: "https://www.wembleycycles.com" },
  { slug: "west-coast-cycles", path: "/shops/west-coast-cycles", name: "West Coast Cycles", cities: ["Perth"], url: "https://westcoastcycles.com.au" },
  { slug: "wheelhaus", path: "/shops/wheelhaus", name: "Wheelhaus", cities: ["Sydney"], url: "https://wheelhaus.com.au" },
  { slug: "wollongong-bike-hub", path: "/shops/wollongong-bike-hub", name: "Wollongong Bike Hub", cities: ["Wollongong"], url: "https://wollongongbikehub.com.au" },
  { slug: "woolys-wheels", path: "/shops/woolys-wheels", name: "Woolys Wheels", cities: ["Sydney"], url: "https://woolyswheels.com.au" },
]

export const SHOP_PATHS = SHOPS.map((s) => s.path)

const BY_SLUG = new Map(SHOPS.map((s) => [s.slug, s]))
const BY_NAME = new Map(SHOPS.map((s) => [s.name, s]))

export function shopBySlug(slug) {
  return BY_SLUG.get(slug) ?? null
}

export function shopByName(name) {
  return BY_NAME.get(name) ?? null
}

// A shop with exactly one city is a storefront you can walk into. Everything
// else is a chain publishing one national catalogue, or an online-only seller
// with no city at all: see docs/vendors.md. The distinction matters because
// filtering the feed to a city does NOT narrow a chain's listing count, so the
// two cannot be ranked in the same table without lying about the numbers.
export function isNational(shop) {
  return shop.cities.length !== 1
}

// Every shop a buyer in `city` can use: the local storefronts plus the chains
// and online sellers that reach it.
export function servesCity(shop, city) {
  return shop.cities.length === 0 || shop.cities.includes(city)
}
