"""initial schema

Revision ID: 8c24986e1289
Revises: 
Create Date: 2026-05-29 14:52:22.010355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c24986e1289'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bikes',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('vendor_name', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('frame_size', sa.Text(), nullable=False),
    sa.Column('price_original', sa.Float(), nullable=True),
    sa.Column('price_sale', sa.Float(), nullable=False),
    sa.Column('discount_percentage', sa.Integer(), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('product_url', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('click_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sku', sa.Text(), nullable=True),
    sa.Column('weight_grams', sa.Integer(), nullable=True),
    sa.Column('product_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('frame_material', sa.Text(), nullable=True),
    sa.Column('drivetrain_groupset', sa.Text(), nullable=True),
    sa.Column('price_drop_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discount_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("category IN ('Road','Mountain','Gravel','E-Bike','Commuter')", name='chk_category'),
    sa.CheckConstraint('discount_percentage >= 0 AND discount_percentage <= 100', name='chk_discount'),
    sa.CheckConstraint('price_sale > 0', name='chk_price'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bikes_brand', 'bikes', ['brand'], unique=False)
    op.create_index('idx_bikes_cat_size_vendor', 'bikes', ['category', 'frame_size', 'vendor_name'], unique=False)
    op.create_index('idx_bikes_category', 'bikes', ['category'], unique=False)
    op.create_index('idx_bikes_city', 'bikes', ['city'], unique=False)
    op.create_index('idx_bikes_click_count', 'bikes', ['click_count'], unique=False)
    op.create_index('idx_bikes_discount_desc', 'bikes', ['discount_percentage'], unique=False)
    op.create_index('idx_bikes_frame_size', 'bikes', ['frame_size'], unique=False)
    op.create_index('idx_bikes_in_stock', 'bikes', ['in_stock'], unique=False)
    op.create_index('idx_bikes_instock_discount', 'bikes', ['in_stock', 'discount_percentage'], unique=False)
    op.create_index('idx_bikes_scraped_at', 'bikes', ['scraped_at'], unique=False)
    op.create_index('idx_bikes_vendor', 'bikes', ['vendor_name'], unique=False)
    op.create_table('scrape_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendor_name', sa.Text(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('bikes_upserted', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribers')
    op.drop_table('scrape_log')
    op.drop_index('idx_bikes_vendor', table_name='bikes')
    op.drop_index('idx_bikes_scraped_at', table_name='bikes')
    op.drop_index('idx_bikes_instock_discount', table_name='bikes')
    op.drop_index('idx_bikes_in_stock', table_name='bikes')
    op.drop_index('idx_bikes_frame_size', table_name='bikes')
    op.drop_index('idx_bikes_discount_desc', table_name='bikes')
    op.drop_index('idx_bikes_click_count', table_name='bikes')
    op.drop_index('idx_bikes_city', table_name='bikes')
    op.drop_index('idx_bikes_category', table_name='bikes')
    op.drop_index('idx_bikes_cat_size_vendor', table_name='bikes')
    op.drop_index('idx_bikes_brand', table_name='bikes')
    op.drop_table('bikes')
    # ### end Alembic commands ###
