// Drop logo files into frontend/public/logos/vendors/ and /brands/
// Any entry whose file is missing will fall back silently to text.

export const VENDOR_LOGOS = {
  '99 Bikes':      '/logos/vendors/99-bikes.png',
  'Bikes Online':  '/logos/vendors/bikes-online.png',
  'Giant':          '/logos/vendors/giant.png',
}

export const BRAND_LOGOS = {
  'Academy':       '/logos/brands/academy.png',
  'Apollo':        '/logos/brands/apollo.png',
  'Avanti':        '/logos/brands/avanti.png',
  'Aventon':       '/logos/brands/aventon.png',
  'Berg':          '/logos/brands/berg.png',
  'BMC':           '/logos/brands/bmc.png',
  'Cannondale':    '/logos/brands/cannondale.png',
  'Cube':          '/logos/brands/cube.png',
  'Focus':         '/logos/brands/focus.png',
  'Giant':         '/logos/brands/giant.png',
  'GT':            '/logos/brands/gt.png',
  'Icon':          '/logos/brands/icon.png',
  'Kellys':        '/logos/brands/kellys.png',
  'Kona':          '/logos/brands/kona.png',
  'KTM':           '/logos/brands/ktm.png',
  'Liv':           '/logos/brands/liv.png',
  'Marin':         '/logos/brands/marin.png',
  'Merida':        '/logos/brands/merida.png',
  'Mongoose':      '/logos/brands/mongoose.png',
  'Moov8':         '/logos/brands/moov8.png',
  'Multicycle':    '/logos/brands/multicycle.png',
  'Norco':         '/logos/brands/norco.png',
  'Pedal':         '/logos/brands/pedal.png',
  'Polygon':       '/logos/brands/polygon.png',
  'Radio':         '/logos/brands/radio.png',
  'Reid':          '/logos/brands/reid.png',
  'REVER':         '/logos/brands/rever.png',
  'Rocky Mountain': '/logos/brands/rocky-mountain.png',
  'Schwinn':       '/logos/brands/schwinn.png',
  'Scott':         '/logos/brands/scott.png',
  'Shogun':        '/logos/brands/shogun.png',
  'Silverback':    '/logos/brands/silverback.png',
  'Specialized':   '/logos/brands/specialized.png',
  'Strider':       '/logos/brands/strider.png',
  'Superior':      '/logos/brands/superior.png',
  'Surly':         '/logos/brands/surly.png',
  'Trek':          '/logos/brands/trek.png',
  'Transition':    '/logos/brands/transition.png',
  'VelectriX':     '/logos/brands/velectrix.png',
  'XDS':           '/logos/brands/xds.png',
  'Yeti':          '/logos/brands/yeti.png',
}
