"""Regenerate frontend/src/content/shops.js from the vendor registry.

The shops tab needs three things the API cannot give it:

  * a stable URL slug per shop, so /shops/<slug> survives a vendor rename
    showing up as a reviewable diff rather than a silently moved page,
  * which cities a shop actually trades in, which lives in the YAML and not in
    the database, and
  * the whole list at *build* time, because scripts/prerender.js is deliberately
    offline and cannot ask the API what shops exist.

So the registry is compiled into a plain-JS module and committed. Run this after
adding, renaming or retiring a vendor:

    python scripts/gen_shops.py

The check mode used by CI fails if the committed file is out of date:

    python scripts/gen_shops.py --check
"""
import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from scrapers.registry import load_registry  # noqa: E402
from scrapers.utils import vendor_slug  # noqa: E402

OUT = Path(__file__).resolve().parent.parent / "frontend" / "src" / "content" / "shops.js"

HEADER = """\
// Generated by scripts/gen_shops.py from scrapers/vendors/*.yaml. Do not edit by
// hand: run `python scripts/gen_shops.py` after adding or renaming a vendor.
//
// Why this file exists rather than an API call: scripts/prerender.js needs the
// full shop list offline, at build time, and a slug has to be stable across a
// vendor rename. `name` is the join key to the API's vendor_name and to
// bikes.vendor_name, so it must match the YAML exactly.
//
// Deliberately dependency-free, for the same reason content/categories.js is:
// prerender.js imports this with bare `node`, outside Vite. No JSX, no imports,
// no import.meta.env.

export const SHOPS = [
"""

FOOTER = """\
]

export const SHOP_PATHS = SHOPS.map((s) => s.path)

const BY_SLUG = new Map(SHOPS.map((s) => [s.slug, s]))
const BY_NAME = new Map(SHOPS.map((s) => [s.name, s]))

export function shopBySlug(slug) {
  return BY_SLUG.get(slug) ?? null
}

export function shopByName(name) {
  return BY_NAME.get(name) ?? null
}

// A shop with exactly one city is a storefront you can walk into. Everything
// else is a chain publishing one national catalogue, or an online-only seller
// with no city at all: see docs/vendors.md. The distinction matters because
// filtering the feed to a city does NOT narrow a chain's listing count, so the
// two cannot be ranked in the same table without lying about the numbers.
export function isNational(shop) {
  return shop.cities.length !== 1
}

// Every shop a buyer in `city` can use: the local storefronts plus the chains
// and online sellers that reach it.
export function servesCity(shop, city) {
  return shop.cities.length === 0 || shop.cities.includes(city)
}
"""


def build() -> str:
    shops = []
    for cfg in load_registry():
        cities = cfg.cities if cfg.cities else ([cfg.city] if cfg.city else [])
        slug = vendor_slug(cfg.vendor_name)
        shops.append(
            {
                "slug": slug,
                "path": f"/shops/{slug}",
                "name": cfg.vendor_name,
                "cities": cities,
                "url": cfg.base_url.rstrip("/"),
            }
        )

    shops.sort(key=lambda s: s["name"].lower())

    # A collision is an error, not a silently suffixed "-2": two shops sharing a
    # slug means one of them is unreachable, and the sitemap would advertise a
    # URL pointing at the other. The fix belongs in the vendor name.
    seen: dict[str, str] = {}
    for shop in shops:
        if shop["slug"] in seen:
            raise SystemExit(
                f"slug collision: {shop['name']!r} and {seen[shop['slug']]!r} "
                f"both produce {shop['slug']!r}. Rename one in its YAML."
            )
        seen[shop["slug"]] = shop["name"]

    lines = []
    for shop in shops:
        fields = ", ".join(f"{k}: {json.dumps(v)}" for k, v in shop.items())
        lines.append(f"  {{ {fields} }},\n")
    return HEADER + "".join(lines) + FOOTER


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the committed file is stale")
    args = parser.parse_args()

    generated = build()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != generated:
            raise SystemExit(
                f"{OUT.relative_to(Path.cwd())} is out of date. "
                "Run: python scripts/gen_shops.py"
            )
        print(f"{OUT.name} is up to date.")
        return

    OUT.write_text(generated, encoding="utf-8", newline="\n")
    print(f"Wrote {OUT} ({generated.count(chr(10))} lines).")


if __name__ == "__main__":
    main()
